/**
 * Re-export of folio-assistant's content-object types. See `builders.ts`.
 *
 * Generated by `folio_init`. Safe to edit; not regenerated.
 */

export type * from "../../../platform/cat-harness/schemas/types";
